### PR TITLE
Added silero VAD for stream stop

### PR DESCRIPTION
**Pull request by whitepail**
If both flags --wake-uri and --vad present - use Silero for VAD during speech streaming and stop streaming after 1 second of silence. Partially fixes rhasspy/wyoming-satellite#20

### CODE REVIEW

**Comment by whitepail** [comment]
More commits were added automatically than I wanted to.
Will recreate the commit with only VAD update.

**Comment by horga83** [comment]
SetVolume does not exist.  This code doesn't run.  It looks like you must have changed wyoming/satellite  but it is not to be found.

**Comment by horga83** [comment]
Nevermind found your wyoming repo.  Any word about etting this included for wyoming-satellite?

**Comment by whitepail** [comment]
It's still WiP.

You can use fist commits - they are only for VAD.
Last commits also allow volume/mic control from both HA and event service.
Volume/mic control from event service is used for hardware buttons mapping
(vol+/vol-/mic mute/force voice command buttons)
You can find my example of event service and zcripts in examples and
scripts folder.

чт, 11 янв. 2024 г., 20:52 horga83 ***@***.***>:

**Pull request closed without merging**
