### PR TITLE
Awake wav mic mute settings

### PR DESCRIPTION
**Pull request by Ranger2959**
Adds two new settings:
- "--mic-seconds-to-mute-after-awake-wav" - seconds to mute mic after awake wav is played.
- "--mic-mute-during-awake-wav" - true/false if mic should be muted while awake-wav is played.

### CODE REVIEW

**Review by llluis — CHANGES_REQUESTED** [review]
You seem to be missing some commits? You add the settings but don't use them anywhere?!...

**Comment by llluis** [comment]
You pass those two settings in the command line and they will be stored in the MicSettings class. However, you are not reading them anywhere, so, there are not being used. 

There's no action in the satellite to use them and mute the mic. 
So, even if you run the satellite with 10s in this parameter, they will be ignored and no mute will be done.

**Review by llluis — APPROVED** [review]
You are absolutely right, sorry. I was expecting this to be new parameters, I wasn't expecting it was just exposing exiting one which was hardcoded in the settings.

**Comment by synesthesiam** [comment]
Thanks!

**Pull request merged**
